### ISSUE TITLE
feat(grid): Introduce responsive and interactive grid

### ISSUE THREAD

**Issue by JaeAeich** [OpenLake/Pixels#3]
## Description
The current grid can be made responsive to the device's height and width. And interactive for users to zoom into the grid if need be.

### Expected outcome
The grid can accustom itself to the device it's been viewed on, and pixels can be zoomed in.

## Proposed solution
Create a container for the grid and style using tailwind to achieve the above-mentioned outcome.

**Comment by tusharbansal22** [comment]
Resolved in #7
